GET http://localhost:8080/bookings

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.length === 0, "Response status is not 200");
});
%}
###
POST http://localhost:8080/bookings
Content-Type: application/json

{ "propertyAddress":  "Konin4", "bookedFrom":  "2023-05-01", "bookedTo":  "2023-05-05"}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
###
GET http://localhost:8080/bookings

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.length === 1, "Response status is not 200");

    });
%}

### Further tests...

####
GET http://localhost:8080/bookings/2212be52-6931-4608-908f-35fe3593f2cf
###
DELETE http://localhost:8080/bookings/...
###
###
PUT http://localhost:8080/bookings/2212be52-6931-4608-908f-35fe3593f2cf
Content-Type: application/json

{ "id":  "2212be52-6931-4608-908f-35fe3593f2cf", "bookedFrom":  "2023-05-01", "bookedTo":  "2023-05-05"}

